#! python3
# data.py - Stores data of states and uts as dict keys and their capitals
# as values

states = {'Andhra Pradesh': 'Amravati',
 'Arunachal Pradesh': 'Itanagar',
 'Assam': 'Dispur',
 'Bihar': 'Patna',
 'Chhattisgarh': 'Raipur',
 'Goa': 'Panaji',
 'Gujarat': 'Gandhinagar',
 'Haryana': 'Chandigarh',
 'Himachal Pradesh': 'Shimla',
 'Jharkhand': 'Ranchi',
 'Karnataka': 'Bengaluru',
 'Kerala': 'Thiruvananthpuram',
 'Madhya Pradesh': 'Bhopal',
 'Maharashtra': 'Mumbai',
 'Manipur': 'Imphal',
 'Meghalaya': 'Shillong',
 'Mizoram': 'Aizwal',
 'Nagaland': 'Kohima',
 'Odisha': 'Bhubaneshwar',
 'Punjab': 'Chandigarh',
 'Rajasthan': 'Jaipur',
 'Sikkim': 'Gangtok',
 'Tamil Nadu': 'Chennai',
 'Telangana': 'Hyderabad',
 'Tripura': 'Agartala',
 'Uttar Pradesh': 'Lucknow',
 'Uttrakhand': 'Dehradun',
 'West Bengal': 'Kolkata'}
uts = {'Andaman and Nicobar Islands': 'Port Blair',
 'Chandigarh': 'Chandigarh',
 'Dadra and Nagar Haveli and Daman & Diu': 'Daman',
 'Jammu and Kashmir': {'Summer': 'Srinagar', 'Winter': 'Jammu'},
 'Ladakh': 'Leh',
 'Lakshdweep': 'Kavarati',
 'New Delhi': 'New Delhi',
 'Puducherry': 'Puducherry'}
